"""``goal-finetune-upet`` — fine-tune a UPET/PET model via metatrain (subprocess).

UPET uses metatensor ``TensorMap`` objects internally; constructing valid,
gradient-carrying TensorMaps from ``AtomicGraph`` requires significant
metatensor machinery.  We deliberately do **not** attempt an in-process
wrapper (unlike MACE/UMA).  Instead this thin CLI:

1. writes a metatrain ``options.yaml`` for the requested base model, and
2. runs ``mtt train`` as a subprocess.

This is acceptable precisely because metatrain is file-based — no gradients
flow through GOAL, so there is nothing to wrap.  The resulting ``.ckpt`` is
then used in GOAL as an MD calculator::

    from goal.md import CalculatorFactory
    calc = CalculatorFactory.create(
        "upet",
        checkpoint_path="runs/upet_finetuned/model.ckpt",
        variants={"energy": "finetune"},
    )

# FUTURE WORK: in-process UPET fine-tuning via a metatensor TensorMap adapter
# (build TensorMap systems from AtomicGraph so UPET can train inside GOALModule
# like MACE/UMA).  Tracked as a placeholder issue — see docs/finetuning/upet.md.

Usage::

    goal-finetune-upet --model pet-omat-l \
        --train data/train.xyz --val data/val.xyz \
        --output runs/upet_finetuned/
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

# Recognised families/sizes (kept in sync with the UPET MD calculator).
_UPET_FAMILIES = ("pet-mad", "pet-oam", "pet-omat", "pet-spice")
_UPET_SIZES = ("xs", "s", "m", "l", "xl")


def _validate_model(model: str) -> None:
    parts = model.rsplit("-", 1)
    family = parts[0] if len(parts) == 2 else model
    size = parts[1] if len(parts) == 2 else ""
    if family not in _UPET_FAMILIES or size not in _UPET_SIZES:
        valid = ", ".join(f"{f}-{{{','.join(_UPET_SIZES)}}}" for f in _UPET_FAMILIES)
        raise SystemExit(f"error: unknown UPET model {model!r}. Valid: {valid}")


def build_options_yaml(
    model: str,
    train_xyz: str,
    val_xyz: str | None,
    output_dir: str,
    epochs: int,
    lr: float,
) -> str:
    """Render a metatrain ``options.yaml`` fine-tuning the given base model.

    The architecture block targets metatrain's PET architecture with a
    ``finetune`` section pointing at the pretrained UPET checkpoint.  Field
    names may need adjusting for your metatrain/upet version — see
    docs/finetuning/upet.md.
    """
    val_block = (
        f"""
validation_set:
  systems:
    read_from: {val_xyz}
    length_unit: angstrom
  targets:
    energy:
      key: energy
      unit: eV
      forces:
        key: forces
"""
        if val_xyz
        else "validation_set: 0.1\n"
    )
    return f"""# Auto-generated by goal-finetune-upet — adjust for your metatrain/upet version.
device: cuda
base_precision: 64

architecture:
  name: pet
  training:
    num_epochs: {epochs}
    learning_rate: {lr}
  finetune:
    method: full
    read_from: {model}   # pretrained UPET base to fine-tune from

training_set:
  systems:
    read_from: {train_xyz}
    length_unit: angstrom
  targets:
    energy:
      key: energy
      unit: eV
      forces:
        key: forces
{val_block}
test_set: 0.0
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="goal-finetune-upet",
        description="Fine-tune a UPET/PET model with metatrain (mtt train subprocess).",
    )
    parser.add_argument("--model", required=True, help="Base UPET model, e.g. pet-omat-l")
    parser.add_argument("--train", required=True, help="Training ExtXYZ file")
    parser.add_argument("--val", default=None, help="Validation ExtXYZ file (optional)")
    parser.add_argument("--output", required=True, help="Output directory for the run")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Write options.yaml but do not launch mtt train.",
    )
    args = parser.parse_args(argv)

    _validate_model(args.model)
    train_path = Path(args.train)
    if not train_path.exists():
        raise SystemExit(f"error: training file not found: {train_path}")

    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    options_path = out_dir / "options.yaml"
    options_path.write_text(
        build_options_yaml(
            model=args.model,
            train_xyz=str(train_path),
            val_xyz=args.val,
            output_dir=str(out_dir),
            epochs=args.epochs,
            lr=args.lr,
        )
    )
    print(f"[upet] wrote {options_path}")

    if args.dry_run:
        print("[upet] --dry-run: skipping `mtt train`.")
        return 0

    if shutil.which("mtt") is None:
        raise SystemExit(
            "error: `mtt` (metatrain) not found on PATH. Install with: "
            "pip install metatrain. See docs/finetuning/upet.md."
        )

    cmd = ["mtt", "train", str(options_path), "-o", str(out_dir / "model.ckpt")]
    print(f"[upet] running: {' '.join(cmd)}")
    completed = subprocess.run(cmd, cwd=str(out_dir), check=False)
    if completed.returncode != 0:
        print(f"[upet] mtt train exited with code {completed.returncode}", file=sys.stderr)
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
