"""Invariant GNN backbone — purely scalar message passing.

A SchNet-like invariant GNN that uses continuous-filter convolutions
with radial basis functions. Outputs invariant (scalar) per-node
features. Satisfies the ``InvariantBackbone`` protocol.

This serves as:
1. A baseline for comparison with equivariant models
2. A fast option when equivariance is not needed
3. A template for implementing other invariant architectures
"""

from __future__ import annotations

import typing

import torch
import torch.nn as nn
from torch_geometric.utils import scatter

from goal.ml.data.graph import AtomicGraph, NodeFeatures
from goal.ml.nn.blocks.embedding import AtomicNumberEmbedding
from goal.ml.nn.primitives.radial import BesselBasis, RadialMLP
from goal.ml.registry import BACKBONE_REGISTRY, MODEL_REGISTRY


class ContinuousFilterConv(nn.Module):
    """Continuous-filter convolution block (SchNet-style).

    Messages are generated by passing edge distances through a filter
    network and multiplying with neighbour features.
    """

    def __init__(
        self,
        hidden_dim: int,
        num_basis: int,
        cutoff: float,
    ) -> None:
        super().__init__()
        self.filter_net = nn.Sequential(
            nn.Linear(num_basis, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )
        self.node_mlp = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )
        self.basis = BesselBasis(num_basis=num_basis, cutoff=cutoff)

    def forward(
        self,
        node_feats: torch.Tensor,
        edge_index: torch.Tensor,
        edge_lengths: torch.Tensor,
    ) -> torch.Tensor:
        row: torch.Tensor
        col: torch.Tensor
        row, col = edge_index  # (E,), (E,)
        basis: torch.Tensor = self.basis(edge_lengths)  # (E, num_basis)
        # ``BesselBasis`` stores its freqs buffer in float64 and emits
        # float64 regardless of the input dtype; cast to the filter net's
        # weight dtype so the boundary is explicit (same pattern as
        # ``RadialMLP``).
        basis = basis.to(self.filter_net[0].weight.dtype)
        filters: torch.Tensor = self.filter_net(basis)  # (E, hidden_dim)
        messages: torch.Tensor = node_feats[col] * filters  # (E, hidden_dim)
        aggregated: torch.Tensor = scatter(
            messages, row, dim=0, reduce="sum", dim_size=node_feats.size(0)
        )  # (N, hidden_dim)
        return node_feats + self.node_mlp(aggregated)  # (N, hidden_dim)


@MODEL_REGISTRY.register("invariant_gnn")
@BACKBONE_REGISTRY.register("invariant_gnn")
class InvariantGNN(nn.Module):
    """Invariant graph neural network backbone.

    SchNet-like architecture using continuous-filter convolutions.
    Outputs scalar per-node features (``irreps = "Nx0e"``).

    Satisfies the ``InvariantBackbone`` protocol.

    Parameters
    ----------
    num_elements : int
        Maximum atomic number supported.
    embedding_dim : int
        Dimension of initial atomic embeddings.
    hidden_channels : int
        Width of hidden layers.
    num_interactions : int
        Number of message-passing layers.
    cutoff : float
        Cutoff radius (Angstrom).
    num_radial_basis : int
        Number of radial basis functions.
    """

    def __init__(
        self,
        num_elements: int = 120,
        embedding_dim: int = 64,
        hidden_channels: int = 128,
        num_interactions: int = 3,
        cutoff: float = 5.0,
        num_radial_basis: int = 20,
    ) -> None:
        super().__init__()
        self._hidden_dim: int = hidden_channels
        self._num_interactions: int = num_interactions

        self.embedding = AtomicNumberEmbedding(
            num_elements=num_elements,
            embedding_dim=embedding_dim,
        )
        self.input_proj = nn.Linear(embedding_dim, hidden_channels)

        self.interactions = nn.ModuleList(
            [
                ContinuousFilterConv(
                    hidden_dim=hidden_channels,
                    num_basis=num_radial_basis,
                    cutoff=cutoff,
                )
                for _ in range(num_interactions)
            ]
        )

    @property
    def hidden_dim(self) -> int:
        return self._hidden_dim

    @property
    def num_interactions(self) -> int:
        return self._num_interactions

    @property
    def irreps_out(self) -> typing.Any:
        """Invariant output: all scalar channels."""
        from e3nn.o3 import Irreps

        return Irreps(f"{self._hidden_dim}x0e")

    def forward(self, graph: AtomicGraph) -> NodeFeatures:
        h: torch.Tensor = self.embedding(graph.z)  # (N, embedding_dim)
        h = self.input_proj(h)  # (N, hidden_channels)

        for interaction in self.interactions:
            h = interaction(  # (N, hidden_channels)
                node_feats=h,
                edge_index=graph.edge_index,  # (2, E)
                edge_lengths=graph.edge_weight,  # (E,)
            )

        return NodeFeatures(
            node_feats=h,  # (N, hidden_channels)
            irreps=f"{self._hidden_dim}x0e",
        )
